### ISSUE TITLE
Duplicated network names

### ISSUE THREAD

**Issue by Robin-Sch** [kotontrion/dotfiles#10]
**Describe the bug**
In the network/wifi tab, some SSID's are duplicated/shown multiple times

**To Reproduce**
1. Open network tab

**Expected behavior**
It should only show distinct network names

**Screenshots**
![image](https://github.com/kotontrion/dotfiles/assets/46354497/3163c501-4124-4d0e-a6ac-c647a2a39973)

**additional information:**
- ags: 1.8.0

**Comment by kotontrion** [comment]
This is expected behavior. Every access point gets its own entry in this list. In this case, the network "Jeannie" has two routers each with 2.4 and 5 GHz, therefore it is listed 4 times here, each of which have the same ssid, but are different access points.

I won't fix this for my ags config, i do however plan on improving this on the gtk4 rewrite of this config.

**Comment by kotontrion** [comment]
As astal is still quite unstable and doesn't seem to improve soon, i decided to address this issue in ags as well.
Access points with the same ssid are now grouped together.
